name: ci
on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    name: sops-ui
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run TruffleHog
        run: |
          docker pull dxa4481/trufflehog
          docker run -v ${{ github.workspace }}:/target dxa4481/trufflehog --entropy=False file:///target
      - name: List files in path
        run: ls -la .
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push sops-ui
        uses: docker/build-push-action@v6
        with:
          context: ./sops-ui
          file: ./sops-ui/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sops-ui:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/sops-ui:${{ env.RELEASE_VERSION }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/sops-ui:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH'
      - name: Run Trivy vulnerability scanner (CRITICAL)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/sops-ui:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'
      - name: Build and push sops-guardians
        uses: docker/build-push-action@v6
        with:
          context: ./sops-guardians
          file: ./sops-guardians/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sops-guardians:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/sops-guardians:${{ env.RELEASE_VERSION }}

      - name: Run Trivy vulnerability scanner sops-guardians
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/sops-guardians:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH'
      - name: Run Trivy vulnerability scanner (CRITICAL) sops-guardians
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_HUB_USERNAME }}/sops-guardians:${{ env.RELEASE_VERSION }}
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL'    
